# Standard Hugo config

baseURL = 'https://nicolasvandenbossche.com/'
languageCode = "en-us"
title = "Home"
theme = "anatole"

# Anatole theme general config

defaultContentLanguage = "en"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Google Analytics

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true 

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe=true
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ''
        hl_inline = false
        lineAnchors = ''
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        noHl = false
        style = 'monokai'
        tabWidth = 4

